# Site settings
title: aidil fitra
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: https://inded.xyz/Jekyll_modern-blog/ # the subpath of your site, e.g. /blog/
url: http://aidil20fitra.github.io/ # the base hostname & protocol for your site
